<script setup lang="ts">
import { useRouter } from 'vue-router'
import { ArrowLeft } from 'lucide-vue-next'

const router = useRouter()
</script>

<template>
  <div class="terms-container">
    <div class="terms-content">
      <button class="back-btn" @click="router.back()">
        <ArrowLeft :size="20" />
        Back
      </button>
      <h1>Terms and Conditions</h1>
      <p class="last-updated">Last Updated: February 17, 2026</p>

      <p>Welcome to Animake. These Terms and Conditions ("Terms") govern your use of the Animake web application and services ("Service"). By accessing or using Animake, you agree to be bound by these Terms. If you do not agree, please do not use the Service.</p>

      <section>
        <h2>1. Description of Service</h2>
        <p>Animake is a SaaS platform that allows users to upload video clips and convert them into digital assets, including Sprite Sheets (.png) and Lottie animations (.json, .lottie). The Service includes video processing features such as trimming (up to 3 seconds), cropping, background removal (chroma keying), and vectorization.</p>
      </section>

      <section>
        <h2>2. Eligibility and Registration</h2>
        <ul>
          <li><strong>Account Creation:</strong> To use certain features, you must register for an account using a valid email or social login.</li>
          <li><strong>Security:</strong> You are responsible for maintaining the confidentiality of your JWT-based authentication credentials. You are liable for all activities occurring under your account.</li>
          <li><strong>Age:</strong> You must be at least 18 years old, or the age of majority in your jurisdiction, to use this Service.</li>
        </ul>
      </section>

      <section>
        <h2>3. Intellectual Property Rights</h2>
        <h3>3.1 User Content</h3>
        <p>You retain all ownership rights to the videos you upload ("User Content") and the assets generated by the Service ("Output").</p>
        <ul>
          <li><strong>Warranty of Ownership:</strong> You represent and warrant that you own or have the necessary licenses, rights, and permissions to use and authorize Animake to process the User Content.</li>
          <li><strong>License to Animake:</strong> By uploading User Content, you grant Animake a worldwide, non-exclusive, royalty-free license to host, store, and process your files solely for the purpose of providing the Service (e.g., converting video to Lottie).</li>
          <li><strong>Copyright Indemnity:</strong> Animake disclaims all liability for copyright infringement resulting from User Content. You agree to indemnify Animake against any legal claims arising from your unauthorized use of third-party media.</li>
        </ul>

        <h3>3.2 Platform Intellectual Property</h3>
        <p>All rights, title, and interest in and to the Service, including the underlying algorithms, software, UI/UX design, logos, and trademarks, remain the exclusive property of Animake. You may not reverse-engineer, decompile, or attempt to extract the source code of our processing engine.</p>
      </section>

      <section>
        <h2>4. Payment, Subscriptions, and Refunds</h2>
        <ul>
          <li><strong>4.1 Freemium Model:</strong> Animake offers a limited free trial (e.g., a set number of generations). We reserve the right to modify or terminate trial offers at any time without notice.</li>
          <li><strong>4.2 Paid Subscriptions:</strong> Once trial limits are reached, continued use of the Service requires a paid subscription or one-time credit purchase. All fees are exclusive of taxes unless stated otherwise.</li>
          <li><strong>4.3 Refund Policy:</strong> All sales are final. Due to the digital nature of the generated assets and the immediate computational costs incurred during processing, we do not offer refunds once a generation has been initiated.</li>
        </ul>
        <p>Optional Clause: Refunds may be considered at our sole discretion within 7 days of purchase only if no assets have been generated using the paid credits/subscription.</p>
      </section>

      <section>
        <h2>5. Acceptable Use and Prohibited Content</h2>
        <p>You agree not to use Animake to process content that:</p>
        <ul>
          <li>Is illegal, hateful, pornographic, or depicts extreme violence.</li>
          <li>Infringes on the intellectual property or privacy rights of others.</li>
          <li>Attempts to bypass the Service's trial limits or automated security measures.</li>
        </ul>
        <p>Animake reserves the right to terminate accounts and delete content that violates these provisions without refund.</p>
      </section>

      <section>
        <h2>6. Service Availability and "As-Is" Warranty</h2>
        <ul>
          <li><strong>No Guarantee of Uptime:</strong> While we strive for 24/7 availability via our Google Cloud infrastructure, we do not guarantee 100% uptime.</li>
          <li><strong>Technical Accuracy:</strong> Our background removal and vectorization tools utilize automated algorithms. We do not guarantee that Output will be error-free. Artifacts, "noise," or inaccuracies in the final Sprite Sheet or Lottie file may occur based on the quality of the source video.</li>
          <li><strong>"As-Is":</strong> The Service is provided "as-is" and "as-available" without warranties of any kind.</li>
        </ul>
      </section>

      <section>
        <h2>7. Limitation of Liability</h2>
        <p>To the maximum extent permitted by law, Animake and its affiliates shall not be liable for any indirect, incidental, special, or consequential damages, including but not limited to:</p>
        <ul>
          <li>Loss of profits or data.</li>
          <li>Technical issues arising from the use of generated assets in third-party engines (e.g., Unity, Web browsers).</li>
          <li>Unauthorized access to your data resulting from user negligence.</li>
        </ul>
        <p>In no event shall Animake's total liability exceed the amount paid by you to Animake in the six (6) months preceding the claim.</p>
      </section>

      <section>
        <h2>8. Data Privacy and Analytics</h2>
        <ul>
          <li><strong>Data Processing:</strong> We process your videos on Google Cloud Platform (GCP) servers. Please refer to our Privacy Policy for details on data retention.</li>
          <li><strong>Analytics:</strong> We use PostHog to track user behavior and usage metrics to improve the platform. By using the Service, you consent to this data collection.</li>
        </ul>
      </section>

      <section>
        <h2>9. Termination</h2>
        <p>We reserve the right to suspend or terminate your account at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users or the business interests of Animake.</p>
      </section>

      <section>
        <h2>10. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of Israel, without regard to its conflict of law provisions.</p>
      </section>

      <section>
        <h2>11. Contact Information</h2>
        <p>If you have any questions about these Terms, please contact us at: <a href="mailto:idanmal8@gmail.com">idanmal8@gmail.com</a>.</p>
      </section>
    </div>
  </div>
</template>

<style scoped lang="scss">
.terms-container {
  min-height: 100vh;
  padding: 4rem 2rem;
  background-color: hsl(var(--background));
  color: hsl(var(--foreground));
  display: flex;
  justify-content: center;
}

.terms-content {
  max-width: 800px;
  width: 100%;

  h1 {
    font-size: 2.5rem;
    margin-bottom: 0.5rem;
    font-weight: 700;
  }

  .back-btn {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    background: none;
    border: none;
    color: hsl(var(--muted-foreground));
    cursor: pointer;
    margin-bottom: 1rem;
    font-size: 1rem;
    padding: 0;
    transition: color 0.2s;

    &:hover {
      color: hsl(var(--foreground));
    }
  }

  .last-updated {
    color: hsl(var(--muted-foreground));
    margin-bottom: 2rem;
    font-size: 0.9rem;
  }

  h2 {
    font-size: 1.5rem;
    margin-top: 2rem;
    margin-bottom: 1rem;
    font-weight: 600;
  }

  h3 {
    font-size: 1.2rem;
    margin-top: 1.5rem;
    margin-bottom: 0.75rem;
    font-weight: 500;
  }

  p {
    line-height: 1.6;
    margin-bottom: 1rem;
    color: hsl(var(--card-foreground));
  }

  ul {
    list-style-type: disc;
    padding-left: 1.5rem;
    margin-bottom: 1rem;

    li {
      margin-bottom: 0.5rem;
      line-height: 1.6;
    }
  }

  strong {
    font-weight: 600;
    color: hsl(var(--foreground));
  }
}
</style>
