export { default as LoginView } from '../views/login/LoginView.vue'
export { default as HomeView } from '../views/home/HomeView.vue'
export { default as VideoChatView } from '../views/video_creation/VideoChatView.vue'
export { default as SpritePreview } from '../views/sprite_preview/SpritePreview.vue'
export { default as CorporateSite } from '../views/corporate_site/CorporateSite.vue'
export { default as TermsAndConditions } from '../views/terms/TermsAndConditions.vue'
